import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Toaster} from "@/components/ui/sonner";
import {AuthProvider} from '@/context/AuthProvider'
import {ThemeProvider} from "@/context/ThemeProvider";
import Footer from "@/components/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <ThemeProvider
          defaultTheme='dark'
          attribute='class'
          enableSystem
          disableTransitionOnChange
      >


      <AuthProvider>
          {children}
          <Footer/>
          <Toaster/>
      </AuthProvider>
      </ThemeProvider>
      </body>
    </html>
  );
}
